config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'car_infos#index'

  resources :car_infos
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_info.rb
# frozen_string_literal: true

class CarInfo < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/car_infos_controller.rb
# frozen_string_literal: true

class CarInfosController < ApplicationController
  before_action :set_car_info, only: %i[show edit update destroy]

  # GET /car_infos
  def index
    @car_infos = CarInfo.all
  end

  # GET /car_infos/1
  def show; end

  # GET /car_infos/new
  def new
    @car_info = CarInfo.new
  end

  # GET /car_infos/1/edit
  def edit; end

  # POST /car_infos
  def create
    @car_info = CarInfo.new(car_info_params)

    if @car_info.save
      redirect_to @car_info, notice: 'Car info was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /car_infos/1
  def update
    if @car_info.update(car_info_params)
      redirect_to @car_info, notice: 'Car info was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /car_infos/1
  def destroy
    @car_info.destroy
    redirect_to car_infos_url, notice: 'Car info was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car_info
    @car_info = CarInfo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_info_params
    params.require(:car_info).permit(:user_id, :car_mark, :car_number, :car_lease_info, :misc_info, :car_type)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/car_infos_helper.rb
# frozen_string_literal: true

module CarInfosHelper
end

app/views/car_infos/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Car Info #<%= car_info.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd><%= car_info.user_id %></dd>

      <dt>Car mark</dt>
      <dd><%= car_info.car_mark %></dd>

      <dt>Car number</dt>
      <dd><%= car_info.car_number %></dd>

      <dt>Car lease info</dt>
      <dd><%= car_info.car_lease_info %></dd>

      <dt>Misc info</dt>
      <dd><%= car_info.misc_info %></dd>

      <dt>Car type</dt>
      <dd><%= car_info.car_type %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back car_info, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_car_info_url(car_info), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to car_info, method: :delete, data: { confirm: "Do you really want to delete this car_info?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(car_info.updated_at) %> ago
  </div>
</div>

app/views/car_infos/_form.html.erb
<% was_validated = car_info.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(car_info, html: form_html_options) do |f| %>
  <div class="form-group">
    <% user_id_class = "form-control" %>
    <% user_id_was_invalid = car_info.errors.include?(:user_id) %>

    <% if was_validated %>
      <% if user_id_was_invalid %>
        <% user_id_class << " is-invalid" %>
      <% else %>
        <% user_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>

    <%= f.number_field :user_id, class: user_id_class, placeholder: "Enter user" %>
    <% if user_id_was_invalid %>
      <% car_info.errors.full_messages_for(:user_id).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% car_mark_class = "form-control" %>
    <% car_mark_was_invalid = car_info.errors.include?(:car_mark) %>

    <% if was_validated %>
      <% if car_mark_was_invalid %>
        <% car_mark_class << " is-invalid" %>
      <% else %>
        <% car_mark_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :car_mark %>

    <%= f.text_field :car_mark, class: car_mark_class, placeholder: "Enter car mark" %>
    <% if car_mark_was_invalid %>
      <% car_info.errors.full_messages_for(:car_mark).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% car_number_class = "form-control" %>
    <% car_number_was_invalid = car_info.errors.include?(:car_number) %>

    <% if was_validated %>
      <% if car_number_was_invalid %>
        <% car_number_class << " is-invalid" %>
      <% else %>
        <% car_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :car_number %>

    <%= f.number_field :car_number, class: car_number_class, placeholder: "Enter car number" %>
    <% if car_number_was_invalid %>
      <% car_info.errors.full_messages_for(:car_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% car_lease_info_class = "form-control" %>
    <% car_lease_info_was_invalid = car_info.errors.include?(:car_lease_info) %>

    <% if was_validated %>
      <% if car_lease_info_was_invalid %>
        <% car_lease_info_class << " is-invalid" %>
      <% else %>
        <% car_lease_info_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :car_lease_info %>

    <%= f.text_field :car_lease_info, class: car_lease_info_class, placeholder: "Enter car lease info" %>
    <% if car_lease_info_was_invalid %>
      <% car_info.errors.full_messages_for(:car_lease_info).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% misc_info_class = "form-control" %>
    <% misc_info_was_invalid = car_info.errors.include?(:misc_info) %>

    <% if was_validated %>
      <% if misc_info_was_invalid %>
        <% misc_info_class << " is-invalid" %>
      <% else %>
        <% misc_info_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :misc_info %>

    <%= f.text_field :misc_info, class: misc_info_class, placeholder: "Enter misc info" %>
    <% if misc_info_was_invalid %>
      <% car_info.errors.full_messages_for(:misc_info).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% car_type_class = "form-control" %>
    <% car_type_was_invalid = car_info.errors.include?(:car_type) %>

    <% if was_validated %>
      <% if car_type_was_invalid %>
        <% car_type_class << " is-invalid" %>
      <% else %>
        <% car_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :car_type %>

    <%= f.text_field :car_type, class: car_type_class, placeholder: "Enter car type" %>
    <% if car_type_was_invalid %>
      <% car_info.errors.full_messages_for(:car_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/car_infos/_list_item.html.erb
<%= link_to car_info, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Car Info #<%= car_info.id %>

    <small class="text-muted">
      <%= time_ago_in_words(car_info.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/car_infos/_table_row.html.erb
<tr>
  <td>
    <%= car_info.user_id %>
  </td>

  <td>
    <%= car_info.car_mark %>
  </td>

  <td>
    <%= car_info.car_number %>
  </td>

  <td>
    <%= car_info.car_lease_info %>
  </td>

  <td>
    <%= car_info.misc_info %>
  </td>

  <td>
    <%= car_info.car_type %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to car_info, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_car_info_url(car_info), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to car_info, method: :delete, data: { confirm: "Do you really want to delete this car_info?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/car_infos/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Car Info #<%= @car_info.id %>
      </h2>

      <div class="card-body">
        <%= render "form", car_info: @car_info %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/car_infos/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Car Infos

      <%= link_to new_car_info_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              User
            </th>

            <th>
              Car mark
            </th>

            <th>
              Car number
            </th>

            <th>
              Car lease info
            </th>

            <th>
              Misc info
            </th>

            <th>
              Car type
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @car_infos, partial: "table_row", as: :car_info %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @car_infos.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :car_info %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Car Infos

        <%= link_to new_car_info_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @car_infos, partial: "list_item", as: :car_info %>
      </div>
    </div>
  </div>
</div>

app/views/car_infos/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Car Info
      </h2>

      <div class="card-body">
        <%= render "form", car_info: @car_info %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/car_infos/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @car_info, partial: "card", as: :car_info %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanillaRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>